version: '3.8'

services:
  db_cicd:
    image: postgres:16.5-alpine
    container_name: grand_operation_farms_cicd_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grand_operation_farms_test
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d grand_operation_farms_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: "no"
    volumes:
      - ./init-cicd.sql:/docker-entrypoint-initdb.d/init-cicd.sql
    # Sem volumes de dados para garantir que o banco seja limpo a cada execução
    # Sem persistência de dados para testes isolados
