# version: '3.8'

services:
  db_dev:
    image: postgres:16.5-alpine
    container_name: prospera_academy_dev_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prospera_academy_dev
    ports:
      - "8432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d prospera_academy_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always